apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: qe
  labels:
    strimzi.io/cluster: kafka-app
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
    cleanup.policy: compact